version: "3.8"

services:
  pesmomat-api:
    image: lgaljo/pesmomat-api:latest
    container_name: pesmomat-api
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - pesmomat-db
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - GENERATOR_API=${GENERATOR_API}
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@pesmomat-db:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      - MONGO2_URI=${MONGO2_URI}
      - SYNC_ENABLED=${SYNC_ENABLED}
      - JWT_SECRET=${JWT_SECRET}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - MAIL_SENDER_NAME=${MAIL_SENDER_NAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_HOST=${MAIL_HOST}

  pesmomat-app:
    image: lgaljo/pesmomat-app:latest
    container_name: pesmomat-app
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      - APP_URL=${APP_URL}
      - APP_PORT=${APP_PORT}
      - API_URL=${API_URL}
      - BROWSE_TIMEOUT=${BROWSE_TIMEOUT}
      - SLIDESHOW_INTERVAL=${SLIDESHOW_INTERVAL}
      - COIN_INTERVAL=${COIN_INTERVAL}
      - ADMIN=${ADMIN}
      - ENABLE_GENERATE=${ENABLE_GENERATE}
      - ENABLE_STATS=${ENABLE_STATS}


  pesmomat-db:
    image: mongo:4
    container_name: pesmomat-db
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ARGS= "--locale-provider=icu --icu-locale=sl-SI"
      - TZ= "Europe/Ljubljana"
      - LANG= "sl_SI.utf8"
    volumes:
      - mongo:/var/lib/mongodb/data
      - /tmp/docker/mongo:/data/db


  pesmomat-generator:
    image: lgaljo/pesmomat-generator
    container_name: pesmomat_generator
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - PATH=${PATH}
      - LANG=${LANG}
      - GPG_KEY=${GPG_KEY}
      - PYTHON_VERSION=${PYTHON_VERSION}
      - PYTHON_PIP_VERSION=${PYTHON_PIP_VERSION}
      - PYTHON_SETUPTOOLS_VERSION=${PYTHON_SETUPTOOLS_VERSION}
      - PYTHON_GET_PIP_URL=${PYTHON_GET_PIP_URL}
      - PYTHON_GET_PIP_SHA256=${PYTHON_GET_PIP_SHA256}


  pesmomat-nginx:
    image: nginx:latest
    container_name: pesmomat-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - pesmomat-api
      - pesmomat-app
    volumes:
      - /home/lukag/default.conf:/etc/nginx/conf.d/nginx.conf:ro


  pesmomat-watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    restart: unless-stopped


volumes:
  mongo:
    name: pesmomat-db
