---
version: "3.8"
services:
  pesmomat-api:
    image: lgaljo/pesmomat-api:latest
    container_name: pesmomat-api
    secrets:
      - pesmi
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      - pesmomat-db
    environment:
      - API_PASSWORD= "/run/secret/pesmi"
      - DATABASE_URL=
      - JWT_ACCESS_SECRET=
      - JWT_REFRESH_SECRET=
  pesmomat-app:
    image: lgaljo/pesmomat-app:latest
    container_name: pesmomat-app
    restart: unless-stopped
    ports:
      - 3200:3200
    environment:
      HOST: 0.0.0.0
      PORT: 3200
      API_URL: null
      NODE_ENV: production
      APP_PASSWORD: /run/secret/pesmi
  pesmomat-db:
    image: mongo
    container_name: pesmomat-db
    restart: unless-stopped
    secrets:
      - pesmi
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -q
        - -U
        - dbuser
    ports:
      - 5433:5432
    environment:
      - MONGO_INITDB_DATABASE=
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD= "/run/secrets/pesmi"
      - MONGO_ROOT_PASSOWORD_FILE= "/run/secrets/pesmi"
      - MONGO_PASSWORD_FILE= "/run/secrets/pesmi"
      - MONGO_DB_PASSWORD_FILE= "/run/secrets/pesmi"
      - MONGO_INITDB_ARGS= "--locale-provider=icu --icu-locale=sl-SI"
      - TZ= "Europe/Ljubljana"
      - LANG= "sl_SI.utf8"
    volumes:
      - mongo:/var/lib/mongodb/data
volumes:
  mongo:
    name: pesmomat-db
secrets:
  pesmi:
    file: pesmi.txt

